spring:
  datasource:
    username: root
    password: 334300
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8000
  tomcat:
    threads:
      max: 1
mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath:/Mapper/*.xml


# Logger Config
logging:
  level:
    com.hexadecimal: debug